### ISSUE TITLE
Installation on gateway v0.4.0

### ISSUE THREAD

**Issue by thgreasi** [DurandA/xiaomi-zigbee-adapter#1]
First of all, :+1: :+1: :+1: for this repo :+1: :+1: :+1: 
I'm facing some issues when trying to install on gateway v0.4.0, cloning & running ./pakcage.sh but it doesn't show up in the list.
According to [the changelog](https://github.com/mozilla-iot/gateway/releases/tag/0.4.0) it seems that they've changed a bunch of paths.

**Comment by thgreasi** [comment]
It seems that it should now be in `~/.mozilla-iot/addons/`.
Interestingly enough the add-on showed up on the list even w/o running `./package.sh`.

**Comment by DurandA** [comment]
Thanks for opening this issue. I will update this package to support gateway v.0.4.0.

I ordered a few Xiaomi sensors so I will add support to more devices soon.

**Comment by DurandA** [comment]
It seems that the API did not change. However, I updated the instructions to install dependencies (`zigbee-shepherd`).

I updated the project to support *WSDCGQ11LM* devices and I will add *WXKG01LM* support soon.

Tell me if you still have some problems using this adapter.
