### ISSUE TITLE
No proper detection in gateway v0.4

### ISSUE THREAD

**Issue by thgreasi** [DurandA/xiaomi-zigbee-adapter#2]
![image](https://user-images.githubusercontent.com/1295829/39085552-02d9b840-458d-11e8-89d1-6511752e3b5e.png)
Tried a WSDCGQ01LM and a WSDCGQ11LM and that's how far I could get.
Using a Digi xstick as per the wiki, so it might be that to blame.

**Comment by DurandA** [comment]
Unlike the [zigbee-adapter](https://github.com/mozilla-iot/zigbee-adapter) from Mozilla, this project is using [zigbee-shepherd](https://github.com/zigbeer/zigbee-shepherd) which is compatible with CC253X; e.g. the cheap [CC2531 USB dongle](https://www.aliexpress.com/wholesale?SearchText=cc2531+usb).

According to your screenshot, you are using the [zigbee-adapter](https://github.com/mozilla-iot/zigbee-adapter) which I think don't have [specific support for Xiaomi devices](https://github.com/mozilla-iot/gateway/issues/707) yet.
