### ISSUE TITLE
How to flash the device on a Mac

### ISSUE THREAD

**Issue by neugartf** [DurandA/xiaomi-zigbee-adapter#3]
I just bought the adapter. Is there a guideline to flash the device with a Mac?

**Comment by DurandA** [comment]
If you don't have Windows and a [CC Debugger](http://www.ti.com/tool/cc-debugger), you can use [CCLib](https://github.com/wavesoft/CCLib) using an Arduino. I successfully used this technique as I don't have any CC Debugger. The usual CC Debugger flashing procedure is described in the [*zigbee2mqtt* wiki](https://github.com/Koenkk/zigbee2mqtt/wiki/Getting-started).

You can have a look on [this discussion](https://github.com/zigbeer/zigbee-shepherd/issues/3) for more details about flashing techniques.

**Comment by neugartf** [comment]
Wow, to be honest, I didn't expect that to be that much work (dont have a Arduino, etc.) 
But thanks for the help :)

**Comment by DurandA** [comment]
I hope that you can find a friend who will do it for you. You only have to do it once. :-)

In the worst case, a CC Debugger + downloader cable is < 15$ on AliExpress. Finding a Windows computer should not be a problem.
